# This is a basic workflow to help you get started with Actions

name: "ms-team-notify"

# Controls when the workflow will run
inputs:
  HOST_NAME:
    type: string
    description: "HOST_NAME"
    required: true
  JOB_NAME:
    type: string
    description: "JOB_NAME"
    required: true
  JOB_NUMBER:
    type: string
    description: "JOB_NUNBER"
    required: true
  ENV:
    type: string
    description: "ENV"
    required: true
  MESSAGE:
    type: string
    description: "MESSAGE"
    required: true
  STATUS:
    type: string
    description: "STATUS"
    required: true

runs:
  using: "composite"
  steps:
    - name: Curl-test
      shell: bash
      id: Curl-test
      run: |
        curl -X POST '${{ inputs.HOST_NAME }}' -H "Content-Type: application/json" -d '{"jobname" : "${{ inputs.JOB_NAME }}","jobnumber" : "${{ inputs.JOB_NUMBER }}","ENV" : "${{ inputs.ENV }}","MESSAGE" : "${{ inputs.MESSAGE }}","STATUS" : "${{ inputs.STATUS }}"}'